//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HypogeumDBConnector.HypogeumWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HypogeumSoap", Namespace="http://www.maionemiky.it/")]
    public partial class Hypogeum : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginUtenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback PartecipaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MuoriOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniziaPartitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinePartitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatoPartitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaPartiteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Hypogeum() {
            this.Url = global::HypogeumDBConnector.Properties.Settings.Default.HypogeumDBConnector_HypogeumWS_Hypogeum;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginUtenteCompletedEventHandler LoginUtenteCompleted;
        
        /// <remarks/>
        public event PartecipaCompletedEventHandler PartecipaCompleted;
        
        /// <remarks/>
        public event MuoriCompletedEventHandler MuoriCompleted;
        
        /// <remarks/>
        public event IniziaPartitaCompletedEventHandler IniziaPartitaCompleted;
        
        /// <remarks/>
        public event FinePartitaCompletedEventHandler FinePartitaCompleted;
        
        /// <remarks/>
        public event StatoPartitaCompletedEventHandler StatoPartitaCompleted;
        
        /// <remarks/>
        public event ListaPartiteCompletedEventHandler ListaPartiteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/LoginUtente", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginUtente(string facebook_key) {
            object[] results = this.Invoke("LoginUtente", new object[] {
                        facebook_key});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginUtenteAsync(string facebook_key) {
            this.LoginUtenteAsync(facebook_key, null);
        }
        
        /// <remarks/>
        public void LoginUtenteAsync(string facebook_key, object userState) {
            if ((this.LoginUtenteOperationCompleted == null)) {
                this.LoginUtenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginUtenteOperationCompleted);
            }
            this.InvokeAsync("LoginUtente", new object[] {
                        facebook_key}, this.LoginUtenteOperationCompleted, userState);
        }
        
        private void OnLoginUtenteOperationCompleted(object arg) {
            if ((this.LoginUtenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginUtenteCompleted(this, new LoginUtenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/Partecipa", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Partecipa(string codice_unet, int id_utente) {
            object[] results = this.Invoke("Partecipa", new object[] {
                        codice_unet,
                        id_utente});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PartecipaAsync(string codice_unet, int id_utente) {
            this.PartecipaAsync(codice_unet, id_utente, null);
        }
        
        /// <remarks/>
        public void PartecipaAsync(string codice_unet, int id_utente, object userState) {
            if ((this.PartecipaOperationCompleted == null)) {
                this.PartecipaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPartecipaOperationCompleted);
            }
            this.InvokeAsync("Partecipa", new object[] {
                        codice_unet,
                        id_utente}, this.PartecipaOperationCompleted, userState);
        }
        
        private void OnPartecipaOperationCompleted(object arg) {
            if ((this.PartecipaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PartecipaCompleted(this, new PartecipaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/Muori", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Muori(string codice_unet, int id_utente, int punti, int posizione) {
            object[] results = this.Invoke("Muori", new object[] {
                        codice_unet,
                        id_utente,
                        punti,
                        posizione});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MuoriAsync(string codice_unet, int id_utente, int punti, int posizione) {
            this.MuoriAsync(codice_unet, id_utente, punti, posizione, null);
        }
        
        /// <remarks/>
        public void MuoriAsync(string codice_unet, int id_utente, int punti, int posizione, object userState) {
            if ((this.MuoriOperationCompleted == null)) {
                this.MuoriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMuoriOperationCompleted);
            }
            this.InvokeAsync("Muori", new object[] {
                        codice_unet,
                        id_utente,
                        punti,
                        posizione}, this.MuoriOperationCompleted, userState);
        }
        
        private void OnMuoriOperationCompleted(object arg) {
            if ((this.MuoriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MuoriCompleted(this, new MuoriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/IniziaPartita", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IniziaPartita(string codice_unet) {
            object[] results = this.Invoke("IniziaPartita", new object[] {
                        codice_unet});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IniziaPartitaAsync(string codice_unet) {
            this.IniziaPartitaAsync(codice_unet, null);
        }
        
        /// <remarks/>
        public void IniziaPartitaAsync(string codice_unet, object userState) {
            if ((this.IniziaPartitaOperationCompleted == null)) {
                this.IniziaPartitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniziaPartitaOperationCompleted);
            }
            this.InvokeAsync("IniziaPartita", new object[] {
                        codice_unet}, this.IniziaPartitaOperationCompleted, userState);
        }
        
        private void OnIniziaPartitaOperationCompleted(object arg) {
            if ((this.IniziaPartitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniziaPartitaCompleted(this, new IniziaPartitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/FinePartita", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FinePartita(string codice_unet) {
            object[] results = this.Invoke("FinePartita", new object[] {
                        codice_unet});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FinePartitaAsync(string codice_unet) {
            this.FinePartitaAsync(codice_unet, null);
        }
        
        /// <remarks/>
        public void FinePartitaAsync(string codice_unet, object userState) {
            if ((this.FinePartitaOperationCompleted == null)) {
                this.FinePartitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinePartitaOperationCompleted);
            }
            this.InvokeAsync("FinePartita", new object[] {
                        codice_unet}, this.FinePartitaOperationCompleted, userState);
        }
        
        private void OnFinePartitaOperationCompleted(object arg) {
            if ((this.FinePartitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinePartitaCompleted(this, new FinePartitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/StatoPartita", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partita StatoPartita(string codice_unet) {
            object[] results = this.Invoke("StatoPartita", new object[] {
                        codice_unet});
            return ((Partita)(results[0]));
        }
        
        /// <remarks/>
        public void StatoPartitaAsync(string codice_unet) {
            this.StatoPartitaAsync(codice_unet, null);
        }
        
        /// <remarks/>
        public void StatoPartitaAsync(string codice_unet, object userState) {
            if ((this.StatoPartitaOperationCompleted == null)) {
                this.StatoPartitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatoPartitaOperationCompleted);
            }
            this.InvokeAsync("StatoPartita", new object[] {
                        codice_unet}, this.StatoPartitaOperationCompleted, userState);
        }
        
        private void OnStatoPartitaOperationCompleted(object arg) {
            if ((this.StatoPartitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatoPartitaCompleted(this, new StatoPartitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.maionemiky.it/ListaPartite", RequestNamespace="http://www.maionemiky.it/", ResponseNamespace="http://www.maionemiky.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Partita[] ListaPartite(System.DateTime dal, System.DateTime al) {
            object[] results = this.Invoke("ListaPartite", new object[] {
                        dal,
                        al});
            return ((Partita[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaPartiteAsync(System.DateTime dal, System.DateTime al) {
            this.ListaPartiteAsync(dal, al, null);
        }
        
        /// <remarks/>
        public void ListaPartiteAsync(System.DateTime dal, System.DateTime al, object userState) {
            if ((this.ListaPartiteOperationCompleted == null)) {
                this.ListaPartiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaPartiteOperationCompleted);
            }
            this.InvokeAsync("ListaPartite", new object[] {
                        dal,
                        al}, this.ListaPartiteOperationCompleted, userState);
        }
        
        private void OnListaPartiteOperationCompleted(object arg) {
            if ((this.ListaPartiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaPartiteCompleted(this, new ListaPartiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.maionemiky.it/")]
    public partial class Partita {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void LoginUtenteCompletedEventHandler(object sender, LoginUtenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginUtenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginUtenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PartecipaCompletedEventHandler(object sender, PartecipaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartecipaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PartecipaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void MuoriCompletedEventHandler(object sender, MuoriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MuoriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MuoriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void IniziaPartitaCompletedEventHandler(object sender, IniziaPartitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniziaPartitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniziaPartitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FinePartitaCompletedEventHandler(object sender, FinePartitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FinePartitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FinePartitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void StatoPartitaCompletedEventHandler(object sender, StatoPartitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatoPartitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatoPartitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partita)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ListaPartiteCompletedEventHandler(object sender, ListaPartiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaPartiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaPartiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Partita[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Partita[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591